[project]
name = "neural-nine"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.127.0",
    "matplotlib>=3.10.8",
    "scikit-learn>=1.8.0",
    "textblob>=0.19.0",
]
